<a href="https://colab.research.google.com/github/salmonin-o3o/ESAA_study/blob/main/ESAA0902%ED%95%84%EC%82%AC%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CH 1. 파이썬 기반의 머신러닝과 생태계 이해
## 03. 넘파이
넘파이(NumPy)는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지.
- 빠른 배열 연산 속도
- 저수준 언어 기반의 호환 API
- 다양한 데이터 핸들링 기능

### 넘파이 ndarray 개요

In [1]:
import numpy as np #as np는 약어 설정,

넘파이의 기반 데이터 타입은 ndarray이다. 다차원 배열을 쉽게 생성하고 연산을 수행할 수 있다.

이때 array()함수로 ndarray를 만든다.

In [4]:
array1 = np.array([1, 2, 3]) #array()의 인자로는 리스트 객체를 주로 사용.
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) #1차원 array로 3개의 데이터

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) #2차원 array로 2X3

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) #2차원 array로 1X3
#행과 열의 수가 튜플 형태임. ndarray 차원을 알 수 있다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


### ndarray의 데이터 타입

ndarray내의 데이터값으로 가능한 것
- 숫자 값(int형, unsigned ind형, float형, complex 타입)
- 문자열 값
- 불 값

단, ndarray내의 데이터 타입은 그 연산의 특성 상 같은 데이터 타입만 가능.(ex. 한개의 ndarray에 int와 float가 함꼐 있을 수 없다.)

In [6]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) #ndarray내의 데이터 타입 확인

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
list2 = [1, 2, 'test'] #데이터 유형이 섞여있는 리스트를 ndarray로 만든다면?
array2 = np.array(list2)
print(array2, array2.dtype) #문자

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) #float

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [13]:
#astype()으로 데이터 타입 변경하기
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1]) # 소수점 이하는 삭제.
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones



In [9]:
sequence_array = np.arange(10) #0부터 10 - 1(= 9)까지 연속된 숫자를 나열해 ndarray의 값으로 변환
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
zeros_array = np.zeros((3, 2), dtype='int32') #튜플 형태로 shape값을 입력
print(zeros_array)
print(zeros_array.dtype, zeros_array.shape)

ones_array = np.ones((3, 2))
print(ones_array)
print(ones_array.dtype, ones_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

In [12]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
#변경이 가능한 형태여야함.
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [16]:
#안자에 -1을 넣어 사용하는 방법
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5) #5개의 칼럼에 맞추어 로우를 생성
print('array2 shape:', array2.shape) #(2, 5)
array3 = array1.reshape(5, -1) #5개의 로우에 맞추어 칼럼를 생성
print('array3 shape:', array3.shape) #(5, 2)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [17]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [19]:
array1= np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist()) #tolist()는 ndarray를 리스트 자료형으로 변환

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1) #reshape(-1,1)과 같은 형태가 자주 사용된다.
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

- 특정한 데이터만 추출(위치를 지정시켜 데이터를 불러오기)
- 슬라이싱(':'사용하기)
- 팬시 인덱싱(인덱싱 집합의 리스트와 ndarray 이용하기)
- 불린 인덱싱(True/False 이용하기)



#### 단일 값 추출

In [20]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [21]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [22]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [23]:
#다차원 ndarray에서 단일 값 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0]) #(axis0 = 0, axis1 = 0)
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1]) #(axis0 = 0, axis1 = 1)
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0]) #(axis0 = 1, axis1 = 0)
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2]) #(axis0 = 2, axis1 = 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


#### 슬라이싱

In [24]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [25]:
# 인덱스 생략 가능
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [26]:
#다차원 ndarray에서 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [27]:
#2차원 ndarray에서 뒤쪽 인덱스를 없앨 경우
print(array2d[0]) #row 인덱스가 0인 것들을 1차원 ndarray로
print(array2d[1]) #row 인덱스가 1인 것들을 1차원 ndarray로
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### 팬시 인덱싱

In [28]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 2], 0:2]
print('array2d[[0, 2], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] => ', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱

In [29]:
array1d = np.arange(start=1, stop=10)
#[]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [30]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [31]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [32]:
Indexes = np.array([5, 6, 7, 8])
array4 = array1d[Indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


필터링 조건을 []안에 기재하면 해당 조건에서 True 값에 해당하는 인덱스값이 저장된다. 이때 저장된 인덱스로 ndarray가 조회되는 과정으로 불린 인덱싱이 동작한다.

### 행렬의 정렬 - sort()와 argsort()

#### 행렬 정렬

In [33]:
#np.sort() vs. ndarray.sort()

org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환 결과:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환 결과:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환 결과: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환 결과: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [34]:
#내림차순

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [35]:
#다차원 ndarray에서 정렬

array2d = np.array([[8, 12],
                   [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기

In [36]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [37]:
#내림차순

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [39]:
#활용 방법

import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### 행렬 내적(행렬 곱)
np.dot()를 사용

In [40]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬
transpose()를 사용

In [41]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
