<a href="https://colab.research.google.com/github/salmonin-o3o/ESAA_study/blob/main/ESAA0902%EB%AC%B8%EC%A0%9C_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [14]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [16]:
arr = np.array([1, 2, 3, 4, 5])
memory_size = array.nbytes
print(f"Memory size of the array:", arr.nbytes)

Memory size of the array: 40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
reversed_vector = np.sort(vector)[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
arr = [1, 2, 0, 0, 4, 0]
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [22]:
identity_matrix  = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [23]:
array = np.random.random((3,3,3))
print(array)

[[[0.98838299 0.07322951 0.93261411]
  [0.51375729 0.83048851 0.44266019]
  [0.33205296 0.95437122 0.54390867]]

 [[0.85043503 0.32608511 0.39767307]
  [0.00414678 0.01150527 0.0893896 ]
  [0.83474848 0.62318256 0.36124257]]

 [[0.03814177 0.31948404 0.68177161]
  [0.66492165 0.69708224 0.77440023]
  [0.11015039 0.37411028 0.67746328]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [24]:
array = np.random.random((10,10))
print(array)
min_value = np.min(array)
max_value = np.max(array)
print("min value:", min_value)
print("max value:", max_value)

[[0.06844544 0.88883783 0.36450062 0.10950066 0.72343855 0.29243762
  0.01214355 0.15260143 0.06759685 0.2847636 ]
 [0.02532973 0.92174413 0.50762651 0.39236879 0.33336909 0.76483291
  0.99129561 0.138346   0.0556604  0.87589125]
 [0.22081437 0.40404855 0.56204847 0.66857228 0.53702899 0.26919112
  0.47172878 0.66732345 0.42307189 0.84997524]
 [0.97290813 0.11284206 0.77218491 0.14618038 0.9554008  0.62567001
  0.25603748 0.32833292 0.15061111 0.25825188]
 [0.65583014 0.05213334 0.02345791 0.60098348 0.03727466 0.02400538
  0.93596419 0.98467032 0.39061575 0.45786847]
 [0.38113175 0.63364522 0.0487357  0.94803342 0.77339119 0.59100891
  0.07249426 0.85398211 0.96170549 0.41976931]
 [0.84528435 0.66244981 0.63622481 0.4557339  0.36119256 0.54845744
  0.90092856 0.43925752 0.13514364 0.71366728]
 [0.26276649 0.71062188 0.8567867  0.88163458 0.07698329 0.58061325
  0.83508958 0.92984117 0.8939684  0.30824169]
 [0.05929633 0.23581294 0.74798284 0.60321921 0.29415214 0.16025973
  0.37606115

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [25]:
vector = np.random.random(30)
print(vector, np.mean(vector))

[0.40888227 0.69420691 0.03797752 0.85943766 0.50737661 0.58641293
 0.23670956 0.12008868 0.54849989 0.59819292 0.94919773 0.5966379
 0.16202163 0.0825283  0.82648263 0.03940522 0.19146775 0.25620415
 0.74070003 0.65980074 0.30763669 0.03062406 0.20578446 0.85402975
 0.33747297 0.13069873 0.46236422 0.50621758 0.37584527 0.32663784] 0.42131808743182386


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
array = np.ones((5,5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [4]:
0 * np.nan

nan

In [5]:
np.nan == np.nan

False

In [6]:
np.inf > np.nan

False

In [7]:
np.nan - np.nan

nan

In [8]:
np.nan in set([np.nan])

True

In [28]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [29]:
matrix = np.zeros((5,5))
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [30]:
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [31]:
np.unravel_index(99, shape=(6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [32]:
matrix = np.random.random((5,5))
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)

[[-0.26788642  0.8351862   0.90000732  1.48242452  0.29266573]
 [ 0.54271634 -1.80404371 -0.35370954 -0.52240885 -1.542218  ]
 [ 1.32360854  1.10289857 -1.17504447  0.2754899  -0.01250556]
 [-0.75688721 -0.28425402 -0.25142212 -0.08202792  1.5811565 ]
 [-1.6496672   1.17751015 -1.51311432  0.86045971 -0.15893413]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [34]:
color_dtype = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
print(color_dtype)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3